# Generated by Django 2.0.2 on 2018-03-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azureAD_auth', '0004_auto_20180222_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present')], default='ABSENT', max_length=10)),
                ('feedback', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.ImageField(default='/media/Default/noImage.png', upload_to='media/Club/')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('ST', 'Started'), ('ED', 'Ended'), ('CC', 'Cenceled')], default='PD', max_length=2)),
                ('image', models.ImageField(default='/media/Default/noImage.png', upload_to='media/Event/')),
                ('venue', models.CharField(max_length=200)),
                ('additional_info', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Event')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Club')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='azureAD_auth.AzureADUser')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_file', models.FileField(blank=True, upload_to='media/etc/')),
                ('additional_info', models.TextField(blank=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='azureAD_auth.AzureADUser')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizing_chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizing_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Club'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.EventTime'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Participant'),
        ),
    ]
