# Generated by Django 2.0.1 on 2018-02-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_desp', models.CharField(max_length=1000)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PD', 'Pendding'), ('ST', 'Started'), ('ED', 'Ended'), ('CC', 'Cenceled')], default='PD', max_length=2)),
                ('image', models.ImageField(default='http://mattislist.com/marketingapp/postimage/noimageavailable.png', upload_to='media/Event/')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_venue', models.CharField(max_length=200)),
                ('organizing_chairman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='society.Member')),
            ],
            options={
                'ordering': ('status', 'event_start'),
            },
        ),
    ]
