# Generated by Django 2.0.1 on 2018-03-09 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('club_desp', models.CharField(max_length=200)),
                ('club_icon', models.ImageField(default='/default/noImage.png', upload_to='media/Club/')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('club_name',),
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/default/noImage.png', upload_to='media/Event/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizing_chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizing_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='society.Club'),
        ),
    ]
