# Generated by Django 2.0.2 on 2018-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('event_id', models.CharField(default='None', max_length=50)),
                ('attendance', models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present')], default='ABSENT', max_length=10)),
                ('additional_info', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
    ]
