# Generated by Django 2.0.2 on 2018-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
