# Generated by Django 2.0.2 on 2018-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureAD_auth', '0002_auto_20180210_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureaduser',
            name='library_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='azureaduser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
