# Generated by Django 2.0.2 on 2018-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureAD_auth', '0003_auto_20180221_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureaduser',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='azureaduser',
            name='year_of_study',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
